### ISSUE TITLE
 ERROR  Failed to compile with 9 errors

### ISSUE THREAD

**Issue by kossa** [eloquentbit/trivia#1]
Hello,

I'm using node v8.9.4 with npm 5.6.0 when I run : npm run dev , I get this error

![image](https://user-images.githubusercontent.com/1175584/35353635-0e58eb98-0148-11e8-9918-e9bb76507509.png)

**Comment by eloquentbit** [comment]
Hi @kossa,
I've updated the code with for the latest version of Nuxt.js.
Now it should compile without errors.

**Comment by kossa** [comment]
Hi @eloquentbit ,
I got a new error

![image](https://user-images.githubusercontent.com/1175584/35719279-ff96e9be-07e8-11e8-9196-e02df7da0057.png)

**Comment by eloquentbit** [comment]
Hi @kossa ,
I think you have another instance of server on port 3000: can you please check?

**Comment by kossa** [comment]
Ahh alright, my bad
